### ISSUE TITLE
[SDK BUG] Pinned Widgets with 'Enabled Clickthrough' aren't actually click through on PC Startup

### ISSUE THREAD

**Issue by jurkog** [microsoft/XboxGameBarSamples#102]
**Describe the bug**
Pinned Widgets with 'Enabled Clickthrough' aren't actually click through on PC Startup until the Game Bar is opened and closed (Win + G pressed twice consecutively)

**To Reproduce**
1. Pin any widget.
2. Press 'Enable Click-through' in the Game bar menu.
3. Restart your PC and wait for the pinned widget to boot on startup, DONT press Win + G prior.
4. Try clicking inside the boundaries of the widget.

**Expected behavior**
Pinned widget with 'Enabled Clickthrough' should always be click through.

**Screenshots**
I took a video, I hope this helps :)

https://www.youtube.com/watch?v=y2a292AyMxM

**Desktop (please complete the following information):**
- OS version: Windows 10 Pro, Version 10.0.19042 Build 19042
- Game Bar version: 5.521.3093.0
- SDK version: 5.3.200605002

**Comment by jurkog** [comment]
I noticed with the most recent version of Game Bar v5.621.4142.0, the widgets no longer start on startup?

**Comment by vidager** [comment]
Hi jurkog,

Yes we are aware of this and it's a difficult problem to solve.  Due to how underlying windows handles the multiple HWNDs, we needed to come to the foreground (WinGForeground) before we could twiddle the settings to get click-through back on.  We've learned some more since we last looked at this, so I'll revisit and see if we can do better.

As far as game bar loading after reboot:  This doesn't happen automatically, something has to trigger game bar to start.  Some things that do this are: 1) If the user has startup tips enabled on game bar, it will launch when a known game launches. 2) Known Game List updates are checked for (infrequent periodic check), 3) Normal game bar hotkey presses, 4) Xbox app (Game Pass) is launched, 5) URI launch.  You likely just didn't hit one of these cases when you were testing v5.621.4142.0?  You can verify manually by running ms-gamebar://launch after reboot.  If you see your pinned widgets appear, then everything is working as expected. 

Due to the above, we've discussed internally what to do with pinned widgets on game bar startup.  We're waiting for the experience team to review the scenario, but by default we enter PinnedOnly mode on startup, thus why the pinned Widgets show.  Since we aren't auto launch, it does create a unpredictable outcome on reboot.  One possibility is we don't show pinned widgets until the user brings Game Bar to the foreground for the first time in a given session, but we're still discussing.  If we went with this solution, the click-through problem described above would be a non-issue. 

Hopefully that was transparent into what's going on. 

Thank you for the feedback!
Ben

**Comment by jurkog** [comment]
Hi Ben,

Is there any update on this?

This is probably our most pressing issue at the moment that we have no control over.

I don't know what happened but this is what I've noticed:
1) Game Bar widgets are still launching at boot without any activation.
2) When they are launched, users cant click through the pinned widgets. We've been advising them to press Win + G twice to bypass this but it's not good that this is a problem in the first place. A lot of people either refund the app, leave a bad review, etc
3) ms-gamebar://launch doesn't work for me anymore. It seemed like it did at one point and now it doesn't. I read the documentation about the URI launch and none of it works for me.

Best,
Jurko

**Comment by SandraPapo** [comment]
Hey Ben,

The possibility you listed would be a great solution to what our customers have been complaining about. I have attached some support emails we have gotten to give you a better representation of the customer's mindset when they encounter the bug. 

![219951019_332921965144152_6929338334614330786_n](https://user-images.githubusercontent.com/22330709/126386142-33595fb8-632f-4944-8d7b-c5dc9cfe7ae6.png)
![221781481_367935538094071_977294803071669391_n](https://user-images.githubusercontent.com/22330709/126386166-85f2a7ef-7920-4e38-bfc5-8adc0e4ea196.png)
![218055483_865043111112698_6249265491572949985_n](https://user-images.githubusercontent.com/22330709/126386183-01cc9d36-3660-44b0-abfe-5d16764a8298.png)
![217461801_533301234646779_8656083733708170977_n](https://user-images.githubusercontent.com/22330709/126386199-f1e62f28-5b39-4b9a-918a-d40d7cda8e2f.png)
![219879988_529067908539556_11707412403961266_n](https://user-images.githubusercontent.com/22330709/126386216-b892efc9-0712-412a-859a-c23f0746619b.png)

Since there is just a lot of confusion around where the bug is originating from, it would be a good call to not show the pinned widgets until the game bar is activated. We always instruct the customers on how to resolve the issue but this bug doesn't look good on us or the game bar platform. 

Hope this info helps,

Best,
Sandra

**Comment by vidager** [comment]
Hi Jurkog and Sandra,

Thank you for the feedback here again.  That clarification helps.  Given that game bar shouldn't shutdown with widgets pinned, this should only occur if game bar crashes or the system reboots. However, it sounds like you have real scenarios where this is a problem for our joint customers. So I will run this by our Program Manager team to see if we can suppress showing pinned widgets until after the user explicitly brings up game bar at least once. 

Sorry for the trouble here.

Thanks,
Ben

**Comment by vidager** [comment]
Update.

I just realized I had already fixed this issue in our 2108 branch.  Pinned widgets won't appear until the first time the user brings game bar to the foreground.  We just reviewed this behavior as a team and agreed to ship it for 2108.  

You should already see this behavior in 5.721.7151.0 version of game bar (July 15th build) which flighted to External Fast and SDK flight rings (if you're in either of those). 

Regarding ms-gamebar://launch.  This URI command only launches game bar if it's not already running.  If it wasn't already running, it starts and enters PinnedOnly mode. It does not toggle Foreground/PinnedOnly states.  So ms-gamebar://launch effectively does nothing if game bar is already running.

Here's the summary difference between 2106 (and prior) and 2108+ when doing ms-gamebar://launch (or any other background activation) when game bar wasn't already running:
   2106 (and prior) - Game bar enters PinnedOnly mode and shows pinned widgets. Click through is not enabled, even if the user has it turned on.  Click through won't be enabled until after the first time game bar comes to foreground (Win+G or other method). 
   2108+ - Game bar enters PinnedOnly mode and does not show pinned widgets.  Click through isn't relevant as no widgets should be shown.  Pinned widgets are not shown until after the first time game bar comes to foreground (Win+G or other method).

Let us know if you have other questions!

Thanks,
Ben

**Comment by vidager** [comment]
Closing this as it should be resolved per the above.  If you see any further issues, please let us know!  Thanks!
