### ISSUE TITLE
Vulkan API Support 

### ISSUE THREAD

**Issue by jurkog** [microsoft/XboxGameBarSamples#103]
**Is your feature request related to a problem? Please describe.**
Customers have expressed frustration to us that our Game bar widget does not work in games running with Vulkan API instead of DirectX. Red Dead Redemption 2 is a good example.

**Describe the solution you'd like**
Ideally, seamless Vulkan API support for Game Bar widgets.

**Describe alternatives you've considered**
I direct all customer support inquiries to run their game in DirectX 11/12 instead of Vulkan if they have the option. Many times they've explicitly asked for Vulkan support and I know that's not in my control.

**Comment by vidager** [comment]
Unfortunately Game Bar as a platform is unable to run over Vulkan.  Because Game Bar doesn't use dll injection into the game's process, it needs to rely on Windows tech to display over the game.  Vulkan bypasses much of the windows graphics stack, including the portion Game Bar operates in. 

Thanks,
Ben

**Comment by jurkog** [comment]
Thank you Ben! That makes sense, I really appreciate the detailed response.
