### ISSUE TITLE
[SDK BUG] ForegroundWorkHandler and XboxGameBarForegroundWorker not found

### ISSUE THREAD

**Issue by Razzile** [microsoft/XboxGameBarSamples#49]
In the advanced samples provided `ForegroundWorkHandler` and `XboxGameBarForegroundWorker` classes are not found. Were they removed from the nuget package perhaps?

**Comment by vidager** [comment]
Hi Razzile,

Very sorry about this.  We made a mistake here.  We do our releases as a triplet: Game Bar, NuPkg, and Samples update. However, last minute we decided to hold back this update due to issues in the new flow for this XboxGameBarForegroundWorker API. Unfortunately this samples update still got merged into master.  Our apologies. We'll back this PR out and all these updates should be back soon!

I'll resolve this issue once we've backed out the PR. 

Thanks,
Ben

**Comment by hamiltonia** [comment]
The change has been reverted. Closing this.
