### ISSUE TITLE
[QUESTION] What's the themesource that supports Xbox Gamebar theme?

### ISSUE THREAD

**Issue by sliptrixx** [microsoft/XboxGameBarSamples#67]
I noticed that all Microsoft made widgets support the theme specified by a user in the gamebar settings. What's the themesource that developers should use to support the theme mentioned?

**Comment by hamiltonia** [comment]
`XboxGameBarWidget` exposes an `ElementTheme` property and event for when it changes. 

https://docs.microsoft.com/en-us/gaming/game-bar/api/xgb-widget#game-bar-state

**Comment by WizardCM** [comment]
Currently the solution seems to be to write your own stylesheet.

**Comment by joshhunt** [comment]
I remember struggling to try and implement theming. I got somewhere by setting RequestedTheme on each Page element, but I ran into some problems (which I can't recall).

I would appreciate a more realistic example of how we're supposed to implement theming, rather than hard coding individual colours in the code-behind event handler

**Comment by totallymonkey** [comment]
I would recommend following the general guidance for UWP apps and how to implement theming. Please take a look at this documentation to see if it helps better understand how to do this:

https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/xaml-theme-resources

I agree with you that the samples could do a better job of showing how to implement theming properly. I can get a work item filed to improve that in the future. Please let me know if you have any more questions.
