### ISSUE TITLE
[SDK BUG] Pinned widgets capture mouse when minimized

### ISSUE THREAD

**Issue by Dawider10** [microsoft/XboxGameBarSamples#68]
**Describe the bug**
Pinned widgets capture mouse and block interaction with underlying applications after being minimized.

**To Reproduce**
1. Pin widget.
2. Minimize widget.
3. Try to interact with underlying application in the area where the widget was located.

**Expected behavior**
Pinned widget should not capture mouse after being minimized.

**Screenshots**
![gamebar](https://user-images.githubusercontent.com/10184683/86650117-b6496980-bfe2-11ea-82ff-a099f8622219.gif)

**Desktop:**
- OS version: Windows 10 1909 build 18363.900
- Game Bar version 5.320.6242.0
- SDK version: 5.3.200605002

**Comment by hamiltonia** [comment]
Hi @Dawider10 - we call the ability to click-through a widget (wait for it...) click-through mode. In the home bar at the top you'll notice a button that has a mouse icon. In your image it shows as click-through disabled, that is: the mouse is enabled and you can interact with your widget when it is pinned. If you enable click-through, the mouse icon becomes disabled, and afterwards all widgets will no longer respond to mouse input when pinned.

**Comment by Dawider10** [comment]
Hi @hamiltonia, I know about the click-through mode but my widget needs interaction.
What I want to achieve is automatically get my widgets out of the way when I detect that the user wants to interact with the underlying app. This way he doesn't have to toggle the click-through mode manually every time.

So this is expected behavior? I wouldn't expect a minimized window to capture mouse input, because (wait for it...) it's minimized. :^)

**Comment by hamiltonia** [comment]
I see now - are you intentionally hiding content in your widget when pinned? Do you have some use case where the widget would show something when pinned, but not all the time? To me this looks like a case where the widget should not allow the pinned state if it doesn't plan to show something when pinned. I.e. don't hide your content when pinned, or attempt to managed the pinned state on your own. 

Re: getting a out of the way when I would disturb the normal usage of the app, Game Bar has no way to understand the users intent, we do not know if the user intends to interact with the widget or the app. The intent is for the widgets usage to be clear, none of the Game Bar widgets allow themselves to be fully transparent when pinned for this reason - we want the user to know that the widget is there so that it makes sense why they can't click through it.

Long term we also want to allow per-widget click through settings; possibly then we could allow the widget to manage the click-through state on their own to allow for cases where they're transparent (or minimized) with no interaction, vs. visible. This is not currently possible due to other technical constraints that we can't modify at this time.

**Comment by Dawider10** [comment]
> I see now - are you intentionally hiding content in your widget when pinned? Do you have some use case where the widget would show something when pinned, but not all the time?

Yes, this is my goal - showing something and hiding it when user wants to interact with the underlying app. But widget also needs to stop capturing the mouse.
I thought that minimizing would be the solution. I thought it would hide the widget **and** stop capturing the mouse.

In my other project a pinned widget is showing some information to the user from time to time. It stays transparent most of the time but it doesn't need interaction so it can be used with the click-through mode enabled.

> Game Bar has no way to understand the users intent, we do not know if the user intends to interact with the widget or the app.

But my widget can detect this because it has connection with the underlying app.

> Long term we also want to allow per-widget click through settings; possibly then we could allow the widget to manage the click-through state on their own to allow for cases where they're transparent (or minimized) with no interaction, vs. visible.

That would be perfect.

**Comment by Dawider10** [comment]
What I would also want to do is opening a widget in pinned state so user doesn't have to pin it manually. My widgets are supposed to be an overlay for the underlying app. I would like to achieve a seamless usage without having to constantly open the Game Bar.

**Comment by hamiltonia** [comment]
> I thought that minimizing would be the solution. I thought it would hide the widget and stop capturing the mouse.

Are you calling GameBarWidget::MinimizeAsync()? If so when? It sounds like you're trying to minimize at some point (after you receive the GameBarDisplayModeChanged event?) and the widget is not minimized, hence intercepting click events. If so we'd need to evaluate if the minimize event is working properly when in pinned mode.

This brings some other questions to mind:
- How does your widget react when not over the top of your own application? Do your application use foreground or some other mechanism to determine the user has it focused, and give this information to the widget?
- If you own the other application why do you need Game Bar for this? Why not build an overlay system into your application?

> What I would also want to do is opening a widget in pinned state so user doesn't have to pin it manually. My widgets are supposed to be an overlay for the underlying app. I would like to achieve a seamless usage without having to constantly open the Game Bar.

Yes - however our platform isn't designed, nor can it support this model right now. There are both technical, security and user experience issues we need to work through. The technical issues are currently not solvable without larger changes to the OS and Game Bar, I don't expect we'll be able to support this soon.

In the near future we are looking at mechanisms for widgets to provide notifications to the user. Can you describe the scenario and what information you wish to convey to your user in these situations? Possibly they could help in your situation.

**Comment by Dawider10** [comment]
> Are you calling GameBarWidget::MinimizeAsync()? If so when?

I tried to minimize using `GameBarWidgetControl::MinimizeAsync(String appExtensionId)` and `GameBarWidget::MinimizeAsync()` after clicking a button.
I also tried to minimize the widget manually, like you can see in the gif included in the bug report.
Ultimately, my widget should minimize on specified event in the underlying application (like opening the menu). I didn't get to develop this feature yet. The widget is in early development.

> - How does your widget react when not over the top of your own application? Do your application use foreground or some other mechanism to determine the user has it focused, and give this information to the widget?
> - If you own the other application why do you need Game Bar for this? Why not build an overlay system into your application?

I don't own the other application. I'm only using the data that it sends. It's a game. I would like to for example minimize a widget when user goes into the menu so he can interact with the in-game menu without any issues.

It would be nice if the widget could open automatically after opening the application. Something like per-app widget configuration in Game Bar would be a solution. I guess I should post a new issue requesting this feature.

> In the near future we are looking at mechanisms for widgets to provide notifications to the user. Can you describe the scenario and what information you wish to convey to your user in these situations? Possibly they could help in your situation.

No, they wouldn't help in this situation. I need to display some information incessantly and hide it in some scenarios.
When it comes to my other project, which displays some information from time to time, notifications also wouldn't be useful unless they allow a completely custom UI. This information is details about the currently played track (title, artist, cover).
This is how it looks like:
![image](https://user-images.githubusercontent.com/10184683/86835692-c1f96680-c09c-11ea-9d6d-9429b75a3859.png)

**Comment by hamiltonia** [comment]
> It would be nice if the widget could open automatically after opening the application. 

We're working on a feature that would allow for an application to activate Game Bar and a widget, but this would require that your application is installed with the widget in the same package. It doesn't sound like this is the case for you. We're not currently planning to allow arbitrary activation as it would be too easy to abuse.

>  I need to display some information incessantly and hide it in some scenarios.
When it comes to my other project, which displays some information from time to time

I sounds like the ability to minimize and restore your pinned widget through the API should meet your needs, assuming we fix the issue where the minimized widget doesn't take input (which we just checked in the fix for, but won't be available broadly until the 20.08 release). However we will not allow you to programmatically pin/unpin or change the click-through state, we believe these are actions only a user should control.

**Comment by Dawider10** [comment]
> We're not currently planning to allow arbitrary activation as it would be too easy to abuse.

What if only the user could set what apps should activate the widget?

> I sounds like the ability to minimize and restore your pinned widget through the API should meet your needs

Yes, but assuming you...

> fix the issue where the minimized widget doesn't take input

You mean where the minimized widget **takes** input, right? Because that's the issue I'm facing.

**Comment by hamiltonia** [comment]
>We're not currently planning to allow arbitrary activation as it would be too easy to abuse.
What if only the user could set what apps should activate the widget?

One of the areas we're investigating for many scenarios is providing the user ability to determine capabilities (e.g can a widget use the microphone, know which game is playing, show notifications, launch other widgets, etc.), this would also need to be considered.

>fix the issue where the minimized widget doesn't take input
You mean where the minimized widget takes input, right? Because that's the issue I'm facing.

A pinned widget should not take input when minimized.

**Comment by vidager** [comment]
Quick note:  

Regarding the original issue you posted with the GIF. We're testing a fix now.  We just had a bug where we left that rectangle region calculated in the canvas area we kept overlaid when Game Bar went into PinnedOnly mode.  We needed to ensure that rect is cleared when a pinned widget is minimized.

**Comment by vidager** [comment]
Hi Dawider10,  can you confirm if the issue for which this issue is titled (Pinned widgets capture mouse when minimized) is resolved in the latest Game Bar?

Thanks!
Ben

**Comment by Dawider10** [comment]
Yep, it's fixed. Thanks!
