### ISSUE TITLE
[Question] How to respond correctly to XboxGameBarWidget.RequestedThemeChanged?

### ISSUE THREAD

**Issue by marck7jr** [microsoft/XboxGameBarSamples#85]
Whenever I try to set the new value of XboxGameBarWidget.RequestedTheme an exception with message "The application called an interface that was marshalled for a different thread. (Exception from HRESULT: 0x8001010E (RPC_E_WRONG_THREAD))" is throwed. I tried run an action using the Window.Current.Dispatcher and CoreApplication.MainView.CoreWindow.Dispatcher but without success. So, how can I do it?

**Comment by totallymonkey** [comment]
Hi. In order to ensure you are on the right thread you have to use a dispatcher that is associated with your widget UI thread. Likely, by using Window.Current.Dispatcher and CoreApplication.MainView.CoreWindow.Dispatcher it is the wrong dispatcher. In our sample code we use an element in the view's dispatcher, something like this:         
co_await resume_foreground(RequestedThemeTextBlock().Dispatcher());

You could also save the dispatcher off when your widget instance is activated in OnActivated, so that way you know you are using the right dispatcher. Let me know if you still aren't able to get it to work.

**Comment by vidager** [comment]
I'm going to resolve this question.  Please reactivate if your question wasn't answered or you still have issues. Thanks!
