### ISSUE TITLE
[SDK BUG] Can't have transparent widget while Game Bar is open

### ISSUE THREAD

**Issue by jurkog** [microsoft/XboxGameBarSamples#87]
**Describe the bug**
As of the late October update, one can't have a fully transparent widget while the Game Bar is open.

**To Reproduce**
Launch any widget (WidgetAdvSampleCS for example) and try to make it transparent while the Game Bar is open. You can't do it. RequestedOpacity doesn't change unless you close the Game bar and have the widget pinned.

**Expected behavior**
If you make the Background property of the page (MainPage.xaml) and the AppManifest's VisualElements.BackgroundColor property equal to "transparent", it should be transparent.

**Desktop (please complete the following information):**
- OS version: Windows 10 20H2
- Game Bar version 5.420.11102.0
- SDK version: 5.3.200605002

**Additional context**
This used to work up until the Game Bar update in late October.

**Comment by vidager** [comment]
Hi jurkog,

Thank you for reporting. We'll investigate and see what's happening. 

Thanks,
Ben

**Comment by jurkog** [comment]
Hi Ben,

Thank you for looking into this, let me know if you need any additional information, I'd even be happy to hop on a call with you and give you a walk through of how this issue affects our product on the Game Bar. My business email is jurko@centerpointgaming.com

Best,
Jurko

**Comment by vidager** [comment]
Hi Jurko,

I circled back with the team and we discussed this.  We performed a lot of user experience adjustments in the 2010 release last year, and one of those was ensuring all widgets (including our inbox ones) had a opaque backplate while in foreground (with the exception that some widgets will show transparency during settings preview modes).  However, based on your feedback and understanding the value of positioning your widget with transparency, we're going to look at allowing this again in 2104 (april release).  I did a quick test just turning off our backplate in WinGForeground mode, but it will regress some of the 3rd party widgets in the store (they rely on that solid backplate in foreground).  Due to this, we'll likely introduce a manifest flag you can specify that says "let me control opacity in foreground"... or something to that affect. 

Sorry for this regression to your scenario and we'll try to have a solution as soon as possible.   We unfortunately cannot fix for 2102 (Feb) as we're already in final testing for that release.

**Comment by jurkog** [comment]
Hi Ben,

Thank you so much for the update! This is great news for us as we (and our users) really miss the previous functionality. Really forward to the April release. Let me know if there's anything you need from our end.

Thanks again,
Jurko

**Comment by vidager** [comment]
VSO: 31425937

**Comment by jurkog** [comment]
Hi Ben,

Any update on this? We've been eagerly waiting for the release this April and any update on this would be much appreciated.

Best Regards,
Jurko

**Comment by vidager** [comment]
Hi Jurko,

Yes this is implemented, along with a center widget API.  You can see the code for both feature usage in the samples branch "prerelease". However, we haven't pushed a game bar build that supports these features or the corresponding NuGet as we discovered a MSVC compiler bug in our early flights (yes surprising) that was causing significant crashes.  MSVC team is investigating and we're trying to get unblocked ASAP for our April release.   Sorry for the delay.

Thanks,
Ben

**Comment by jurkog** [comment]
Hi Ben,

I really appreciate your swift response and update. No problem, we're really looking forward to the update!

Thanks again,
Jurko

**Comment by vidager** [comment]
2104 version of Game Bar and SDK that supports centering API and transparency while in foreground.  _please note the pkg-manifest doc page for how to enable transparency in foreground_

SDK on NuGet.org
https://www.nuget.org/packages/Microsoft.Gaming.XboxGameBar/5.6.210414002

Docs updates here
https://docs.microsoft.com/en-us/gaming/game-bar/api/xgb-widget
https://docs.microsoft.com/en-us/gaming/game-bar/guide/pkg-manifest

Please note when you build against the new SDK and release it, in the rare case users acquire your new widget without acquiring the 2104 game bar, they will be instructed to upgrade game bar in order to launch your widget.  The link to upgrade game bar will be shown directly in your widget window.  After updating Game Bar, your widget will load.  Again this should be a rare occurrence for users.

**Comment by jurkog** [comment]
Hi Ben,

Words cannot express the joy we felt seeing the transparency and centering features work on our end. Thank you and the Game bar team for this and all of your extended support.

Best regards,
Jurko & Sandra from CenterPoint Gaming
