### ISSUE TITLE
How do I allow my app to be detected by game bar as a game?

### ISSUE THREAD

**Issue by BurkusCat** [microsoft/XboxGameBarSamples#89]
I wasn't able to find a good place to post this but here seemed the most appropriate. I have developed a UWP game using Xamarin.Forms. It doesn't use DirectX/OpenGL etc. It is a game though. How can I ensure game bar automatically detects this app as a game without the user needing to manually flag it for gamebar?

**Comment by hamiltonia** [comment]
If you're publishing your game through the Microsoft store, and it's categorized as a game, then it will automatically be detected by Game Bar. If you're publishing through a 3rd party store, we regularly update an internal list with known games, we would need to know where it's published so that we could review it before adding it.

**Comment by BurkusCat** [comment]
Perfect, thank you! :) Its not currently available on stores but it is good to know that is the identification mechanism (I thought there may be a method for my app itself to identify itself as a game to game bar).
