### ISSUE TITLE
Customers are asking for widget centering

### ISSUE THREAD

**Issue by SandraPapo** [microsoft/XboxGameBarSamples#90]
**Background:**
My name is Sandra and I am reaching out to request a feature on behalf of the Crosshair X community. Crosshair X is a rapidly growing custom crosshair overlay app that uses a game bar widget to overlay games. We are currently in the top 5 widgets on the widget store and we love the game bar platform. 

**The Problem:**
We are getting multiple support emails every day asking for a button that just automatically centers the widget. 
Our current solution involves instructing the user to drag the widget to the desired location and then using hotkeys to move the crosshair pixel by pixel until it's in the center.
[Link to gif](https://cdn.discordapp.com/attachments/805267265833402389/805270206602936360/image0.gif)
As you can see, it is quite tedious and not intuitive for the customer. 

**The Solution:**
There are a few ways to solve the problem but at the end of the day, we are just trying to easily center our widget. 
The following are the two solutions that I can think of to solve the issue.
1. An API that lets us get and set the coordinates of the widget.
2. An API call that automatically centers the widget
Either one of these solutions would allow us to give our customers the feature they have been asking for.

**Comment by vidager** [comment]
VSO: 31952358
VSO: 31614416

**Comment by vidager** [comment]
2104 version of Game Bar and SDK that supports centering API.

SDK on NuGet.org
https://www.nuget.org/packages/Microsoft.Gaming.XboxGameBar/5.6.210414002

Docs updates here
https://docs.microsoft.com/en-us/gaming/game-bar/api/xgb-widget
https://docs.microsoft.com/en-us/gaming/game-bar/guide/pkg-manifest

Please note when you build against the new SDK and release it, in the rare case users acquire your new widget without acquiring the 2104 game bar, they will be instructed to upgrade game bar in order to launch your widget.  The link to upgrade game bar will be shown directly in your widget window.  After updating Game Bar, your widget will load.  Again this should be a rare occurrence for users.

**Comment by vidager** [comment]
Closing this as 2104 delivered the centering feature.
